#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Daniel Polo
"""Agent-runnable consistency lint for egl-utils-go (generated by EADOS).

A dependency-free (Python 3 standard library only) checker that asserts the project is
internally congruent after any change. Run from anywhere in the repo:

    python tools/consistency_lint.py

It exits non-zero with an actionable report when a congruence invariant is violated. The
contract (the "congruence checks"):

  1. version-lockstep — the version constant, the README `Status-vX.Y.Z` badge, and the
     latest released changelog/release file (if any) agree;
  2. adr-index       — every docs/adr/NNNN-*.md is indexed and every indexed ADR exists,
     with sequential numbering and no gap;
  3. patterns        — every Implemented/Planned catalogue row cites an existing ADR and an
     existing code location under the source tree;
  4. spec-map        — the ROADMAP Spec Coverage Map has no dangling row;
  5. milestones      — README ↔ ROADMAP milestone-completion state is consistent and no
     checkbox is malformed;
  6. bugs            — every docs/bugs/ record has valid frontmatter, its filename/path
     agrees with its id/discovered date, ids are unique and non-gapped, the index ↔ files
     bijection holds, and a `fixed` record names its `fixed-in`;
  7. i18n-freshness  — (only when i18n is enabled) no translated page is staler than its
     English source;
  8. posture         — AGENTS.md's enterprise-posture declaration and the compliance
     register exist together or not at all (asserted in both directions);
  9. action-pins     — every `uses:` in .github/workflows/ names a 40-character commit
     digest and carries the `# vX.Y.Z` comment that makes the pin reviewable;
 10. workflow-permissions — no workflow grants a token scope at the workflow level, every
     job declares its own, and a `write` scope appears only where it is allowlisted;
 11. ledger-coverage  — every ADR that defers a capability with the canonical
     `Deferred, additive:` marker is cited by the additive-capability ledger (ADR-0057),
     and every ADR the ledger cites exists;
 12. readme-packages  — the README's Packages section names exactly the feature packages
     that exist under the source root, asserted in both directions.

Each check is independent; all run, then the report lists every failure. The checks are
designed to PASS on a freshly-generated repository (empty catalogues, no releases yet).

Checks 9 and 10 (ADR-0056) and 11 (ADR-0057) live here rather than in a policy tool of
their own because `consistency / lint` is already a required status check on master, and a
new CI job does not become a required context until someone adds it by hand.

Generated configuration is in the CONFIG block below — EADOS fills it from project.yaml.
"""

import os
import re
import subprocess
import sys

# ---------------------------------------------------------------------------
# CONFIG — filled by EADOS at generation time from orchestrator/project.yaml.
# ---------------------------------------------------------------------------
CONFIG = {
    # The file holding the version constant, relative to the repo root, or None if the
    # version lives only in a build manifest the lint should not parse. When None (or the
    # file is absent), version-lockstep derives the source version from the README badge.
    "version_file": "version.go",   # ADR-0045: module metadata stays at the module root
    # A regex with a single (\d+\.\d+\.\d+) group that extracts the version from that file.
    "version_regex": r"(\d+\.\d+\.\d+)",
    # The source root that pattern code-locations must live under.
    "src_main": "pkg",              # ADR-0045: feature packages live under pkg/
    # Whether documentation i18n is enabled (gates check 7).
    "i18n_enabled": False,
}

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
failures = []  # list of (check_name, message)


def fail(check, message):
    failures.append((check, message))


def read(*parts):
    with open(os.path.join(ROOT, *parts), encoding="utf-8") as handle:
        return handle.read()


def exists(rel):
    return os.path.exists(os.path.join(ROOT, rel))


def git(*args):
    try:
        out = subprocess.run(
            ["git", "-C", ROOT, *args], capture_output=True, text=True, check=True
        )
        return out.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


def semver_tuple(text):
    m = re.search(r"(\d+)\.(\d+)\.(\d+)", text)
    return tuple(int(g) for g in m.groups()) if m else None


# ---------------------------------------------------------------------------
# 1. Version lockstep
# ---------------------------------------------------------------------------
def check_version_lockstep():
    name = "version-lockstep"
    readme = read("README.md")
    bm = re.search(r"Status-v(\d+\.\d+\.\d+)", readme)
    if bm is None:
        fail(name, "no `Status-vX.Y.Z` badge found in README.md")
        return
    badge = bm.group(1)

    # Source of truth: the version file if present, else the badge itself.
    source = badge
    vf = CONFIG.get("version_file")
    if vf and exists(vf):
        text = read(*vf.split("/"))
        vm = re.search(CONFIG["version_regex"], text)
        if vm is None:
            fail(name, f"could not parse a version from {vf} with the configured regex")
            return
        source = vm.group(1)
        if badge != source:
            fail(name, f"README badge v{badge} != version file {vf} ({source})")

    # Latest released changelog file (per-version split), if any exist.
    cl_dir = os.path.join(ROOT, "docs", "changelog")
    cl = []
    if os.path.isdir(cl_dir):
        for cur, _d, files in os.walk(cl_dir):
            for fn in files:
                m = re.fullmatch(r"v(\d+\.\d+\.\d+)\.md", fn)
                if m:
                    cl.append(m.group(1))
    if cl:
        latest = max(cl, key=semver_tuple)
        if latest != source:
            fail(name, f"latest docs/changelog v{latest} != source version {source}")

    # Latest release-notes file, if any exist.
    rel_dir = os.path.join(ROOT, "docs", "releases")
    rel = []
    if os.path.isdir(rel_dir):
        for fn in os.listdir(rel_dir):
            m = re.fullmatch(r"v(\d+\.\d+\.\d+)\.md", fn)
            if m:
                rel.append(m.group(1))
    if rel:
        latest = max(rel, key=semver_tuple)
        if latest != source:
            fail(name, f"latest docs/releases/v{latest}.md != source version {source}")


# ---------------------------------------------------------------------------
# 2. ADR index bijection + sequential numbering
# ---------------------------------------------------------------------------
def check_adr_index():
    name = "adr-index"
    adr_dir = os.path.join(ROOT, "docs", "adr")
    if not os.path.isdir(adr_dir):
        fail(name, "docs/adr/ directory is missing")
        return
    files = sorted(fn for fn in os.listdir(adr_dir) if re.fullmatch(r"\d{4}-.+\.md", fn))
    if not files:
        fail(name, "no ADR files found (expected at least 0001 and 0002)")
        return
    index = read("docs", "adr", "README.md")
    for fn in files:
        if fn[:-3] not in index:
            fail(name, f"ADR '{fn[:-3]}' is not listed in docs/adr/README.md")
    nums = [int(fn[:4]) for fn in files]
    for i, n in enumerate(nums, start=1):
        if n != i:
            fail(name, f"ADR numbering gap/dup: expected {i:04d}, found {n:04d}")
            break
    for num in re.findall(r"\]\((\d{4}-[a-z0-9-]+\.md)\)", index):
        if not os.path.exists(os.path.join(adr_dir, num)):
            fail(name, f"index links missing ADR file '{num}'")


# ---------------------------------------------------------------------------
# 3. Catalogued patterns -> ADR + code location (tolerant of an empty catalogue)
# ---------------------------------------------------------------------------
def check_patterns():
    name = "patterns"
    if not exists("docs/patterns/README.md"):
        fail(name, "docs/patterns/README.md is missing")
        return
    cat = read("docs", "patterns", "README.md")
    # Real Implemented/Planned rows start with `| <digits> |`. The `| — |` placeholder row is
    # ignored, so a freshly-generated empty catalogue passes.
    rows = re.findall(r"^\|\s*\d+\s*\|.*\|.*$", cat, re.MULTILINE)
    catalogued = [r for r in rows if "Implemented" in r or "Planned" in r]
    for row in catalogued:
        pattern = row.split("|")[2].strip()
        adrs = re.findall(r"\((?:\.\./)*adr/(\d{4}-[a-z0-9-]+\.md)\)", row)
        if not adrs:
            fail(name, f"pattern '{pattern}': no ADR link in its row")
        for adr in adrs:
            if not exists(os.path.join("docs", "adr", adr)):
                fail(name, f"pattern '{pattern}': ADR '{adr}' does not exist")
        # Code locations are repo-relative paths under CONFIG["src_main"] ("." = the repo
        # root, ADR-0003). ADR/doc links are excluded; whatever remains must exist on disk.
        src_root = (CONFIG.get("src_main") or ".").strip("/")
        raw = re.findall(r"\((?:\.\./)*([A-Za-z0-9_][A-Za-z0-9_./-]*)\)", row)
        # A code location looks like a path (contains '/' or ends in .go); a bare
        # parenthesized symbol like `(pubsub.Broker)` in the problem cell is prose.
        code = [p for p in raw
                if not p.startswith(("adr/", "docs/"))
                and ("/" in p or p.endswith(".go"))]
        if src_root not in ("", "."):
            code = [p for p in code if p == src_root or p.startswith(src_root + "/")]
        if not code:
            fail(name, f"pattern '{pattern}': no source code location in its row")
        for path in code:
            if not exists(path):
                fail(name, f"pattern '{pattern}': code location '{path}' does not exist")


# ---------------------------------------------------------------------------
# 4. Spec Coverage Map — no dangling row
# ---------------------------------------------------------------------------
def check_spec_map():
    name = "spec-map"
    roadmap = read("ROADMAP.md")
    block = re.search(r"## Spec Coverage Map.*?(?=\n## |\Z)", roadmap, re.DOTALL)
    if block is None:
        fail(name, "no '## Spec Coverage Map' section in ROADMAP.md")
        return
    glyphs = {"⏳", "🚧", "✅", "❎"}
    seen = 0
    for line in block.group(0).splitlines():
        if not line.startswith("| §"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 4:
            fail(name, f"malformed Spec Coverage Map row: {line.strip()}")
            continue
        seen += 1
        section, items, status = cells[0], cells[2], cells[3]
        if not items:
            fail(name, f"spec row {section} has an empty 'Roadmap items' cell (dangling)")
        if not any(g in status for g in glyphs):
            fail(name, f"spec row {section} has no recognised status glyph: '{status}'")
    if seen == 0:
        fail(name, "Spec Coverage Map has no '| §...' rows")


# ---------------------------------------------------------------------------
# 5. ROADMAP <-> README milestone completion consistency
# ---------------------------------------------------------------------------
def check_milestones():
    name = "milestones"
    readme = read("README.md")
    roadmap = read("ROADMAP.md")
    readme_status = {}
    for m in re.finditer(r"^\|\s*(\d+)\s*\|[^|]+\|\s*([^|]+?)\s*\|$", readme, re.MULTILINE):
        readme_status[int(m.group(1))] = "✅" in m.group(2)
    if not readme_status:
        fail(name, "no milestone table rows parsed from README.md")
        return
    sections = re.split(r"^## Milestone (\d+)", roadmap, flags=re.MULTILINE)
    roadmap_complete = {}
    for i in range(1, len(sections), 2):
        num = int(sections[i])
        body = sections[i + 1].split("\n## ")[0]
        items = re.findall(r"^- \[([ xX])\]\s", body, re.MULTILINE)
        if items:
            roadmap_complete[num] = all(c.lower() == "x" for c in items)
    for num, complete in readme_status.items():
        if complete and num in roadmap_complete and not roadmap_complete[num]:
            fail(name, f"README marks Milestone {num} complete, but ROADMAP has "
                       "unchecked item(s) in that milestone")
    for ln in roadmap.splitlines():
        if re.match(r"^- \[", ln) and not re.match(r"^- \[[ xX]\]\s", ln):
            fail(name, f"malformed ROADMAP checkbox: {ln.strip()[:60]}")


# ---------------------------------------------------------------------------
# 6. Bug ledger integrity
# ---------------------------------------------------------------------------
BUG_STATUSES = {"open", "confirmed", "fixed", "wontfix", "rejected", "duplicate",
                "cannot-reproduce"}   # `rejected`: an unsubstantiated report (ledger README, #242)
BUG_SEVERITIES = {"low", "medium", "high", "critical"}
BUG_REPORTERS = {"internal", "third-party"}
BUG_REQUIRED = ("id", "title", "status", "severity", "reporter", "discovered")


def _parse_frontmatter(text):
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end == -1:
        return None
    fields = {}
    for line in text[3:end].splitlines():
        if not line.strip() or ":" not in line:
            continue
        key, _, value = line.partition(":")
        fields[key.strip()] = value.strip()
    return fields


def check_bugs():
    name = "bugs"
    bugs_dir = os.path.join(ROOT, "docs", "bugs")
    if not os.path.isdir(bugs_dir):
        return
    index_path = os.path.join(bugs_dir, "README.md")
    index = read("docs", "bugs", "README.md") if os.path.exists(index_path) else ""
    numbers = []
    for cur, _d, files in os.walk(bugs_dir):
        for fn in files:
            m = re.fullmatch(r"BUG-(\d{4})-[a-z0-9-]+\.md", fn)
            if not m:
                continue
            num = int(m.group(1))
            rel = os.path.relpath(os.path.join(cur, fn), bugs_dir).replace(os.sep, "/")
            fm = _parse_frontmatter(read("docs", "bugs", *rel.split("/")))
            if fm is None:
                fail(name, f"{rel}: missing or malformed YAML frontmatter")
                continue
            for key in BUG_REQUIRED:
                if not fm.get(key):
                    fail(name, f"{rel}: missing required frontmatter key '{key}'")
            if fm.get("id") != f"BUG-{m.group(1)}":
                fail(name, f"{rel}: frontmatter id '{fm.get('id')}' != filename BUG-{m.group(1)}")
            if fm.get("status") and fm["status"] not in BUG_STATUSES:
                fail(name, f"{rel}: unknown status '{fm['status']}'")
            if fm.get("severity") and fm["severity"] not in BUG_SEVERITIES:
                fail(name, f"{rel}: unknown severity '{fm['severity']}'")
            if fm.get("reporter") and fm["reporter"] not in BUG_REPORTERS:
                fail(name, f"{rel}: unknown reporter '{fm['reporter']}'")
            disc = fm.get("discovered", "")
            dm = re.fullmatch(r"(\d{4})-(\d{2})-\d{2}", disc)
            if not dm:
                fail(name, f"{rel}: discovered '{disc}' is not YYYY-MM-DD")
            elif f"{dm.group(1)}/{dm.group(2)}/" not in rel:
                fail(name, f"{rel}: path does not match discovered date {disc}")
            if fm.get("status") == "fixed" and not fm.get("fixed-in"):
                fail(name, f"{rel}: status 'fixed' requires a 'fixed-in' release")
            if f"({rel})" not in index:
                fail(name, f"{rel} is not linked from docs/bugs/README.md index")
            numbers.append(num)
    if numbers:
        if len(set(numbers)) != len(numbers):
            fail(name, "duplicate BUG ids found")
        for i, n in enumerate(sorted(numbers), start=1):
            if n != i:
                fail(name, f"BUG numbering gap/dup: expected {i:04d}, found {n:04d}")
                break
    for link in re.findall(r"\]\((\d{4}/\d{2}/BUG-\d{4}-[a-z0-9-]+\.md)\)", index):
        if not os.path.exists(os.path.join(bugs_dir, link)):
            fail(name, f"index links missing bug file '{link}'")


# ---------------------------------------------------------------------------
# 7. i18n freshness (only when enabled)
# ---------------------------------------------------------------------------
def check_i18n_freshness():
    name = "i18n-freshness"
    if not CONFIG.get("i18n_enabled"):
        return
    manifest_rel = os.path.join("docs", "i18n", "translation-status.md")
    if not exists(manifest_rel):
        fail(name, f"i18n enabled but {manifest_rel} is missing")
        return
    manifest = read("docs", "i18n", "translation-status.md")
    i18n_dir = os.path.join(ROOT, "docs", "i18n")
    for line in manifest.splitlines():
        if not line.lstrip().startswith("| ["):
            continue
        if "`translated`" not in line:
            continue
        link = re.search(r"\]\(([^)]+)\)", line)
        sha = re.search(r"\|\s*`([0-9a-f]{7,40})`\s*\|", line)
        if link is None or sha is None:
            fail(name, f"could not parse translated manifest row: {line.strip()}")
            continue
        src = os.path.normpath(os.path.join(i18n_dir, link.group(1)))
        rel = os.path.relpath(src, ROOT).replace(os.sep, "/")
        newer = git("log", "--oneline", f"{sha.group(1)}..HEAD", "--", rel)
        if newer is None:
            fail(name, f"git unavailable or commit {sha.group(1)} not in history for {rel}")
        elif newer:
            fail(name, f"i18n translation of {rel} is STALE ({len(newer.splitlines())} "
                       "commit(s) after the recorded source commit)")


# ---------------------------------------------------------------------------
# 8. Enterprise posture ↔ compliance register (ADR-0015 / #248)
# ---------------------------------------------------------------------------
# The posture must not be prose-only. If AGENTS.md declares the enterprise posture, the
# compliance register (docs/compliance/README.md) must exist; and the register must not exist
# without the declaration. Two directions so neither the doc nor the AGENTS.md clause can drift
# out on its own — the same both-ways discipline the ADR-index and bug-ledger checks use.
_ENTERPRISE_MARKER = "enterprise governance posture"


def check_posture():
    name = "posture"
    agents = read("AGENTS.md") if exists("AGENTS.md") else ""
    declared = _ENTERPRISE_MARKER in agents
    register = exists("docs/compliance/README.md")
    if declared and not register:
        fail(name, "AGENTS.md declares the enterprise governance posture but "
                   "docs/compliance/README.md (the control register) is missing")
    if register and not declared:
        fail(name, "docs/compliance/README.md exists but AGENTS.md does not declare the "
                   "enterprise governance posture — the register has no posture to serve")


# ---------------------------------------------------------------------------
# 9. Action pins — every third-party Action is referenced by commit digest
# ---------------------------------------------------------------------------
# A `uses:` on a mutable tag runs whatever the upstream owner last pushed to it, so the
# review that approved the workflow approved a moving target. Both halves are required: the
# 40-hex digest, which is what actually pins, and the `# vX.Y.Z` comment, which is what makes
# the pin reviewable and is what Dependabot rewrites when it bumps one (ADR-0056).
#
# This is deliberately here rather than in a fifth policy tool: `consistency / lint` is
# already a required status check on master, and adding a job does not add a required
# context — it has to be added by hand, and until it is, the new gate can go red without
# blocking anything (the trap ADR-0054 recorded).
_USES_RE = re.compile(r"^\s*(?:-\s+)?uses:\s*(?P<ref>\S+)(?P<rest>.*)$")
_DIGEST_RE = re.compile(r"^[0-9a-f]{40}$")
_PIN_COMMENT_RE = re.compile(r"^\s*#\s*v\d+\.\d+\.\d+\s*$")


def _workflow_files():
    """Repo-relative paths of every workflow file, or [] when there are none."""
    wf_dir = os.path.join(ROOT, ".github", "workflows")
    if not os.path.isdir(wf_dir):
        return []
    return [".github/workflows/" + fn
            for fn in sorted(os.listdir(wf_dir))
            if fn.endswith((".yml", ".yaml"))]


def check_action_pins():
    name = "action-pins"
    for rel in _workflow_files():
        for lineno, line in enumerate(read(*rel.split("/")).splitlines(), start=1):
            m = _USES_RE.match(line)
            if m is None:
                continue
            ref, rest = m.group("ref"), m.group("rest")
            # A local action (`./.github/actions/foo`) or a same-repo reusable workflow is
            # this repository's own reviewed code; there is nothing external to pin.
            if ref.startswith("./"):
                continue
            if "@" not in ref:
                fail(name, f"{rel}:{lineno}: `uses: {ref}` has no version at all")
                continue
            repo, _, version = ref.rpartition("@")
            if not _DIGEST_RE.match(version):
                fail(name, f"{rel}:{lineno}: `{repo}` is pinned to '{version}', not a "
                           f"40-character commit digest — a tag can be re-pointed by "
                           f"whoever owns the action")
                continue
            if not _PIN_COMMENT_RE.match(rest):
                fail(name, f"{rel}:{lineno}: `{repo}` is digest-pinned but carries no "
                           f"`# vX.Y.Z` comment, so no reviewer can tell which release "
                           f"{version[:12]}… is")


# ---------------------------------------------------------------------------
# 10. Workflow permissions — the workflow grants nothing, every job asks
# ---------------------------------------------------------------------------
# Two rules, and the second is the one with teeth:
#
#   * no workflow-level grant (`permissions: {}`), because a scope declared there is
#     inherited by every job added to the file later — which is exactly how release.yml
#     came to hand `contents: write` to any future job without anyone deciding to;
#   * every job declares its own block, and a *write* scope must be on the allowlist below.
#
# Enforcing the house indentation (2 for a job key, 4 for its keys) is intentional: this is
# a congruence lint, not a YAML implementation, and it stays standard-library only because
# the `consistency` CI job installs no packages (ADR-0056).
# The trailing `(?:#.*)?` on the scope pattern is load-bearing and was added after the
# check was written: the one job in this repository that holds write scopes documents each
# of them with an end-of-line comment, so a pattern anchored straight to `$` matched none of
# them, saw an empty write set, and passed its own allowlist vacuously. A gate that cannot
# see the case it exists to police is worse than no gate, because it reports green.
_JOB_KEY_RE = re.compile(r"^  ([A-Za-z_][A-Za-z0-9_-]*):\s*$")
_SCOPE_RE = re.compile(r"^      ([a-z][a-z-]*):\s*(read|write|none)\s*(?:#.*)?$")


def _uncommented(line):
    """`line` with a trailing YAML comment removed. Safe here because the lines this is
    applied to are permission mappings, which never contain a quoted '#'."""
    return line.split("#", 1)[0].strip()

# (workflow file, job key) -> the write scopes that job is allowed to hold.
_ALLOWED_WRITES = {
    ("release.yml", "draft-release"): {"contents", "id-token", "attestations"},
}


def check_workflow_permissions():
    name = "workflow-permissions"
    for rel in _workflow_files():
        basename = rel.rsplit("/", 1)[-1]
        lines = read(*rel.split("/")).splitlines()

        top = [ln for ln in lines if ln.startswith("permissions:")]
        if not top:
            fail(name, f"{rel}: no workflow-level `permissions:` — declare "
                       f"`permissions: {{}}` so no job can inherit a scope by default")
        elif _uncommented(top[0]) != "permissions: {}":
            fail(name, f"{rel}: workflow-level permissions is '{_uncommented(top[0])}'; it "
                       f"must be `permissions: {{}}` — a grant here is inherited by every "
                       f"job added to this file later")

        try:
            jobs_at = next(i for i, ln in enumerate(lines) if ln.startswith("jobs:"))
        except StopIteration:
            fail(name, f"{rel}: no `jobs:` block")
            continue

        # Job keys are the only lines indented by exactly two spaces that end in a colon.
        starts = [i for i in range(jobs_at + 1, len(lines)) if _JOB_KEY_RE.match(lines[i])]
        for n, start in enumerate(starts):
            key = _JOB_KEY_RE.match(lines[start]).group(1)
            end = starts[n + 1] if n + 1 < len(starts) else len(lines)
            block = lines[start + 1:end]

            perms_at = [i for i, ln in enumerate(block)
                        if ln.startswith("    permissions:")]
            if not perms_at:
                fail(name, f"{rel}:{start + 1}: job '{key}' declares no `permissions:` — "
                           f"with `permissions: {{}}` at the workflow level it would run "
                           f"with no token scope at all")
                continue

            declared = _uncommented(block[perms_at[0]])
            if declared != "permissions:":
                # An inline form (`permissions: {}` / `write-all`) — the first is fine, the
                # second is the opposite of the rule.
                if declared != "permissions: {}":
                    fail(name, f"{rel}:{start + perms_at[0] + 2}: job '{key}' has "
                               f"'{declared}'; spell the scopes out one per line")
                continue

            writes = set()
            for ln in block[perms_at[0] + 1:]:
                scope = _SCOPE_RE.match(ln)
                if scope is None:
                    break  # end of the permissions mapping
                if scope.group(2) == "write":
                    writes.add(scope.group(1))

            allowed = _ALLOWED_WRITES.get((basename, key), set())
            for scope in sorted(writes - allowed):
                fail(name, f"{rel}: job '{key}' grants `{scope}: write`, which is not on "
                           f"this job's allowlist — a write token belongs only to a job "
                           f"that publishes something (ADR-0056). If that is genuinely "
                           f"new, add it to _ALLOWED_WRITES with the reason")


# ---------------------------------------------------------------------------
# 11. Ledger coverage — a deferred capability is registered where it can be found
# ---------------------------------------------------------------------------
# ADR-0057 turns the "Deferred, additive" lines scattered through the design records into
# one ledger with a trigger per entry. Prose in a Consequences section is exactly the kind
# of claim no gate can see, which is how eleven of these came to be discharged without the
# deferring ADR ever being updated — so the register gets a tripwire in both directions:
#
#   * every ADR carrying the canonical marker is cited by the ledger;
#   * every ADR the ledger cites exists.
#
# WHAT THIS CHECK CANNOT SEE, stated rather than discovered (ADR-0043's 12.1 lesson, and
# the workflow-permissions hole above): it keys on the marker, which 13 of the 26 ADRs in
# the ledger use. The rest defer in prose no pattern matches without false positives — "a
# deferred recover()", "Go's `defer` intuition" and "deferring a nil-pointer dereference"
# all appear in these documents and none of them is a deferral. Retrofitting the marker
# into accepted records to please a regex was rejected (ADR-0057); §A is complete by
# census, and this check exists to catch the NEXT deferral, where the marker is free.
_LEDGER = "docs/adr/0057-additive-capability-ledger.md"
_DEFERRAL_MARKER_RE = re.compile(r"deferred[,/]\s*additive", re.IGNORECASE)
_ADR_FILE_RE = re.compile(r"^(\d{4})-.*\.md$")


def check_ledger_coverage():
    name = "ledger-coverage"
    adr_dir = os.path.join(ROOT, "docs", "adr")
    if not os.path.isdir(adr_dir) or not exists(_LEDGER):
        return  # a freshly-generated repo has neither

    ledger = read(*_LEDGER.split("/"))
    # The ledger cites a source as a markdown link whose text is the bare ADR number.
    cited = set(re.findall(r"\[(\d{4})\]\(\d{4}-[^)]*\.md\)", ledger))

    numbers = {}
    for entry in sorted(os.listdir(adr_dir)):
        m = _ADR_FILE_RE.match(entry)
        if m:
            numbers[m.group(1)] = entry

    self_number = _ADR_FILE_RE.match(os.path.basename(_LEDGER)).group(1)

    for number, entry in numbers.items():
        if number == self_number:
            continue
        if _DEFERRAL_MARKER_RE.search(read("docs", "adr", entry)):
            if number not in cited:
                fail(name, f"docs/adr/{entry} defers a capability with the "
                           f"`Deferred, additive:` marker but ADR-{number} is not cited by "
                           f"{_LEDGER} — add its row to §A or §B in this PR, with the "
                           f"trigger that would schedule it (ADR-0057)")

    for number in sorted(cited):
        if number not in numbers:
            fail(name, f"{_LEDGER} cites ADR-{number}, which does not exist under "
                       f"docs/adr/ — a ledger row pointing at nothing is worse than no row")


# ---------------------------------------------------------------------------
# 12. README package inventory — the front door lists exactly what ships
# ---------------------------------------------------------------------------
# The README's "Packages" section is a hand-written table of all 21 feature packages, each
# linking to its pkg.go.dev page. That is the one artifact a reader meets first and the one
# nothing else forces anyone to update, so package 22 would ship documented nowhere and
# nobody would notice. Asserted as a bijection, the same both-ways discipline the ADR index
# and bug ledger use.
#
# WHAT THIS CHECK DOES NOT SEE: it compares the *set* of packages, never the prose beside
# them. A row whose description has gone stale passes. Checking the text against each
# package's doc comment was considered and rejected — the README deliberately paraphrases
# (shorter, and it adds cross-references a doc comment should not carry), so the check would
# either fail on every honest edit or need a similarity threshold nobody can justify.
#
# The name class is deliberately wider than Go's lowercase convention. Anchored to `[a-z]`
# it matched the leading lowercase run of a mistyped link and stopped — `…/pkg/semaphoreX`
# yielded `semaphore`, which is on disk, so a broken link passed. Found by a deliberate
# violation that failed to fail.
_PKGDEV_RE = re.compile(
    r"https://pkg\.go\.dev/github\.com/danielPoloWork/egl-utils-go/v2/pkg/([A-Za-z0-9_-]+)")


def check_readme_packages():
    name = "readme-packages"
    src = os.path.join(ROOT, CONFIG["src_main"])
    if not os.path.isdir(src) or not exists("README.md"):
        return

    on_disk = {
        d for d in os.listdir(src)
        if os.path.isdir(os.path.join(src, d)) and not d.startswith((".", "_"))
    }
    listed = set(_PKGDEV_RE.findall(read("README.md")))

    for pkg in sorted(on_disk - listed):
        fail(name, f"package '{CONFIG['src_main']}/{pkg}' is not listed in README.md's "
                   f"Packages section — a package the front door does not name is one a "
                   f"consumer cannot find")
    for pkg in sorted(listed - on_disk):
        fail(name, f"README.md's Packages section links '{pkg}', which does not exist under "
                   f"{CONFIG['src_main']}/ — the link renders a 404 on pkg.go.dev")


CHECKS = [
    check_version_lockstep,
    check_adr_index,
    check_patterns,
    check_spec_map,
    check_milestones,
    check_bugs,
    check_i18n_freshness,
    check_posture,
    check_action_pins,
    check_workflow_permissions,
    check_ledger_coverage,
    check_readme_packages,
]


def main():
    for fn in CHECKS:
        try:
            fn()
        except Exception as exc:  # a check crashing is itself a failure
            fail(fn.__name__, f"check crashed: {exc!r}")
    if failures:
        print("Consistency lint: FAIL\n")
        for check, message in failures:
            print(f"  [{check}] {message}")
        print(f"\n{len(failures)} congruence problem(s) found.")
        return 1
    print("Consistency lint: OK — all congruence invariants hold.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
